import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: 'white',
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 16,
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 56,
    backgroundColor: 'white',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 20,
    paddingRight: 20,
  },
  main_image: {
    width: 140,
    height: 140,
  },
  icon: {
    width: 24,
    height: 24,
  },
  heading: {
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 36,
    marginBottom: 16,
    color: 'black',
  },
  text: {
    fontSize: 16,
    fontWeight: '500',
  },
  dateText: {
    fontSize: 16,
    color: '#666666',
  },
  chipsBox: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    marginBottom: 16,
  },
  chipPink: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FAACD2',
    borderRadius: 16,
  },
  chipBlue: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#AFBFFA',
    borderColor: '#AFBFFA',
    borderRadius: 16,
  },
  chipYellow: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFE388',
    borderColor: '#FFE388',
    borderRadius: 16,
  },
  chipPinkBorder: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#FF64AE',
    borderRadius: 16,
  },
  chipBlueBorder: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#6889FF',
    borderRadius: 16,
  },
  chipYellowBorder: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#FFD54A',
    borderRadius: 16,
  },
  chipContent: {
    fontSize: 16,
    lineHeight: 22,
    color: 'black',
  },
  chipBorderContent: {
    fontSize: 16,
    lineHeight: 22,
    color: '#666666',
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFD54A',
  },
  disabledButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 56,
    borderRadius: 28,
    backgroundColor: '#DCDCDC',
  },
  buttonGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    width: '100%',
    marginTop: 24,
  },
  buttonContent: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    letterSpacing: 1,
  },
  outlineButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#FFD54A',
  },
  outlineButtonContent: {
    color: '#FFD54A',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    letterSpacing: 1,
  },
  modalHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalImageContainer: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  modal: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  modalImg: {
    width: 260,
    height: 120,
  },
  modalContent: {
    width: '100%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 16,
  },
  modalButtonGroup: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
    gap: 8,
    paddingTop: 16,
  },
  input: {
    width: '100%',
    height: 56,
    marginBottom: 16,
    borderRadius: 28,
    backgroundColor: 'white',
  },
  inputContent: {
    fontSize: 16,
    paddingVertical: 'auto',
    textAlignVertical: 'center',
  },
});
